// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using myapp.Data;

#nullable disable

namespace myapp.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20250401034913_added-data")]
    partial class addeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("myapp.models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Class");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Address = "UK Block",
                            Name = "Grade 11"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Nepal Block",
                            Name = "Grade 12"
                        });
                });

            modelBuilder.Entity("myapp.models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("myapp.models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 11,
                            Gender = "Female",
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 11,
                            Gender = "Male",
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 12,
                            Gender = "Male",
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 11,
                            Gender = "Male",
                            Name = "David"
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 12,
                            Gender = "Female",
                            Name = "Emma"
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 12,
                            Gender = "Male",
                            Name = "Frank"
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 12,
                            Gender = "Female",
                            Name = "Grace"
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 11,
                            Gender = "Male",
                            Name = "Henry"
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 11,
                            Gender = "Female",
                            Name = "Ivy"
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 12,
                            Gender = "Male",
                            Name = "Jack"
                        },
                        new
                        {
                            Id = 11,
                            ClassId = 11,
                            Gender = "Female",
                            Name = "Kate"
                        },
                        new
                        {
                            Id = 12,
                            ClassId = 12,
                            Gender = "Male",
                            Name = "Liam"
                        },
                        new
                        {
                            Id = 13,
                            ClassId = 11,
                            Gender = "Female",
                            Name = "Mia"
                        },
                        new
                        {
                            Id = 14,
                            ClassId = 12,
                            Gender = "Male",
                            Name = "Nathan"
                        },
                        new
                        {
                            Id = 15,
                            ClassId = 12,
                            Gender = "Female",
                            Name = "Olivia"
                        },
                        new
                        {
                            Id = 16,
                            ClassId = 11,
                            Gender = "Male",
                            Name = "Paul"
                        },
                        new
                        {
                            Id = 17,
                            ClassId = 11,
                            Gender = "Female",
                            Name = "Quinn"
                        },
                        new
                        {
                            Id = 18,
                            ClassId = 12,
                            Gender = "Male",
                            Name = "Ryan"
                        },
                        new
                        {
                            Id = 19,
                            ClassId = 12,
                            Gender = "Female",
                            Name = "Sophia"
                        },
                        new
                        {
                            Id = 20,
                            ClassId = 11,
                            Gender = "Male",
                            Name = "Thomas"
                        });
                });

            modelBuilder.Entity("myapp.models.Student", b =>
                {
                    b.HasOne("myapp.models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("myapp.models.Class", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
